name:                TMCRTracker
version:             0.2.0.0
github:              "Ibot02/TMCRTracker"
license:             BSD3
author:              "Ibot02"
maintainer:          "jtp.jtp@gmx.de"
copyright:           "2019 Ibot02"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Ibot02/TMCRTracker#readme>

dependencies:
- base >= 4.7 && < 5
- threepenny-gui
- parsers
- containers
- array
- mtl
- transformers
- parsec
- aeson
- directory
- bytestring

library:
  source-dirs: src

executables:
  TMCRTracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TMCRTracker

tests:
  TMCRTracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TMCRTracker
